# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode11.3
language: swift
#cache: cocoapods
#podfile: Netswift/Podfile
#before_install:
#    - gem install cocoapods # Since Travis is not always on latest version
#    - pod install --project-directory=Netswift
script:
    - set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/Netswift.xcworkspace -scheme Netswift-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
    - pod lib lint
